<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[3]=array(2,1,1,'56uL5byP6LaF5aOw5rOi5raI5q+S5py6');
$cfg_Cs[4]=array(2,1,1,'5LiA5L2T5oyC5byP6LaF5aOw5rOi5raI5q+S5py6');
$cfg_Cs[9]=array(0,1,1,'5bqU55So5qGI5L6L');
$cfg_Cs[10]=array(0,1,1,'5LyB5Lia5bGV56S6');
$cfg_Cs[11]=array(0,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[12]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[13]=array(0,1,1,'5Zyo57q/55WZ6KiA');
$cfg_Cs[14]=array(11,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[15]=array(11,1,1,'6KGM5Lia5Yqo5oCB');
$cfg_Cs[16]=array(11,1,1,'5bi46KeB6Zeu6aKY');
?>