<div  class="pro_one_box" style="width:298px; float:left;">
        <div  class="pro_pic" style="height:300px;"><a href="[field:arcurl/]" title="[field:title /]"><img src="[field:litpic/]" alt="[field:title /]" width="280" height="300" border="0" style="border: 1px solid #C0C0C0"></a></div>
        <div class="pro_name" style="padding-top:5px; padding-bottom:5px;"> <a href="[field:arcurl/]" title="[field:title /]"> [field:title /] </a> </div>
        <div class="clear"></div>
      </div>