<div class="divproduct_new_div_item">
            <div class="divproduct_new_div_item_date"></div>
            <div class="divproduct_new_div_item_content">
              <div class="divproduct_new_div_item_title"><a class="divproduct_new_div_item_a" href="[field:arcurl/]" title="[field:title /]" style="font-size:15px">[field:title /]</a></div>
            </div>
            <div class="product_div_item_pic"> <a href="[field:arcurl/]" title="[field:title /]"> <img src="[field:litpic/]" alt="[field:title /]" class="product_div_item_image"> </a> </div>
          </div>