<div class="shopmrsc">
          <ul>
            <li><a href="[field:arcurl/]" title="[field:title /]" class="xwlb_img" ><img src="[field:litpic/]" alt="[field:title /]"></a> <a href="[field:arcurl/]" title="[field:title /]" style="width:970px;" class="xwlb_content" >
              <p class="xwlbbt">[field:title /]</p>
              <p class="xwlbnr">[field:description function="cn_substr(@me,520)"/]......更多</p>
              <p class="xwlbsj">[field:pubdate function="GetDateMK(@me)"/]</p>
              </a> </li>
          </ul>
        </div>