<?php
$z[0]=Array("field","",128,151);
$z[0][4]=array();
$z[0][4]['name']="id";
$z[1]=Array("global","",164,190);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("field","",222,251);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",355,386);
$z[3][4]=array();
$z[3][4]['name']="typenameen";
$z[4]=Array("field","",464,493);
$z[4][4]=array();
$z[4][4]['name']="typename";
$z[5]=Array("field","",582,605);
$z[5][4]=array();
$z[5][4]['name']="id";
$z[6]=Array("sql"," \r\n            [field:content  function='cn_substr(html2text(@me),400)'/]...\r\n            ",635,796);
$z[6][4]=array();
$z[6][4]['sql']="Select content from dede_arctype where id=1";
$z[7]=Array("field","",858,881);
$z[7][4]=array();
$z[7][4]['name']="id";

?>