<?php
$z[0]=Array("channel","\r\n      <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">\r\n        <h3 class=\"tit\">[field:typename/]</h3>\r\n        <em class=\"icon\"></em></a></li>\r\n      ",182,502);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[0][4]['currentstyle']="<li><a href='list.php?tid=~id~'><h3 class='tit'>~typename~</h3><em class='icon'></em></a></li>";
$z[1]=Array("global","",848,872);
$z[1][4]=array();
$z[1][4]['name']="cfg_beian";
$z[2]=Array("global","",874,898);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",1172,1194);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("type","\r\n    <li><a href=\"list.php?tid=[field:id/]\" title=\"地图\"><s class=\"icon\"></s><span>地图</span></a></li>\r\n    ",1358,1507);
$z[4][4]=array();
$z[4][4]['typeid']="12";
$z[5]=Array("global","",1632,1658);
$z[5][4]=array();
$z[5][4]['name']="cfg_cmspath";
$z[6]=Array("global","",1692,1718);
$z[6][4]=array();
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",1821,1846);
$z[7][4]=array();
$z[7][4]['name']="cfg_weixin";
$z[8]=Array("global","",1848,1873);
$z[8][4]=array();
$z[8][4]['name']="cfg_weixin";
$z[9]=Array("global","",2073,2099);
$z[9][4]=array();
$z[9][4]['name']="cfg_cmspath";

?>