<?php
$z[0]=Array("global","",208,232);
$z[0][4]=array();
$z[0][4]['name']="cfg_phone";
$z[1]=Array("global","",233,255);
$z[1][4]=array();
$z[1][4]['name']="cfg_lxr";
$z[2]=Array("global","",273,295);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",324,346);
$z[3][4]=array();
$z[3][4]['name']="cfg_add";
$z[4]=Array("global","",438,469);
$z[4][4]=array();
$z[4][4]['name']="cfg_beian";
$z[5]=Array("channel","\r\n       <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n       ",1299,1415);
$z[5][4]=array();
$z[5][4]['type']="top";
$z[5][4]['row']="8";
$z[6]=Array("global","",2180,2201);
$z[6][4]=array();
$z[6][4]['name']="cfg_qq";
$z[7]=Array("global","",2517,2541);
$z[7][4]=array();
$z[7][4]['name']="cfg_phone";

?>