<?php
$z[0]=Array("global","",199,223);
$z[0][4]=array();
$z[0][4]['name']="cfg_phone";
$z[1]=Array("global","",224,246);
$z[1][4]=array();
$z[1][4]['name']="cfg_lxr";
$z[2]=Array("global","",264,286);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",315,337);
$z[3][4]=array();
$z[3][4]['name']="cfg_add";
$z[4]=Array("global","",429,460);
$z[4][4]=array();
$z[4][4]['name']="cfg_beian";
$z[5]=Array("channel","\r\n       <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n       ",1287,1403);
$z[5][4]=array();
$z[5][4]['type']="top";
$z[5][4]['row']="8";
$z[6]=Array("global","",2179,2200);
$z[6][4]=array();
$z[6][4]['name']="cfg_qq";
$z[7]=Array("global","",2516,2540);
$z[7][4]=array();
$z[7][4]['name']="cfg_phone";

?>