<?php
$z[0]=Array("channel","\r\n      <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">\r\n        <h3 class=\"tit\">[field:typename/]</h3>\r\n        <em class=\"icon\"></em></a></li>\r\n      ",182,502);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[0][4]['currentstyle']="<li><a href='list.php?tid=~id~'><h3 class='tit'>~typename~</h3><em class='icon'></em></a></li>";
$z[1]=Array("global","",613,639);
$z[1][4]=array();
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",727,751);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",753,777);
$z[3][4]=array();
$z[3][4]['name']="cfg_beian";
$z[4]=Array("global","",1051,1073);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";
$z[5]=Array("type","\r\n    <li><a href=\"list.php?tid=[field:id/]\" title=\"地图\"><s class=\"icon\"></s><span>地图</span></a></li>\r\n    ",1237,1386);
$z[5][4]=array();
$z[5][4]['typeid']="12";
$z[6]=Array("global","",1511,1537);
$z[6][4]=array();
$z[6][4]['name']="cfg_cmspath";
$z[7]=Array("global","",1571,1597);
$z[7][4]=array();
$z[7][4]['name']="cfg_webname";
$z[8]=Array("global","",1700,1725);
$z[8][4]=array();
$z[8][4]['name']="cfg_weixin";
$z[9]=Array("global","",1727,1752);
$z[9][4]=array();
$z[9][4]['name']="cfg_weixin";
$z[10]=Array("global","",1952,1978);
$z[10][4]=array();
$z[10][4]['name']="cfg_cmspath";

?>