<?php
$z[0]=Array("global","",135,161);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",174,200);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("global","",231,257);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",461,486);
$z[3][4]=array();
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n      <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n      ",1348,1562);
$z[4][4]=array();
$z[4][4]['type']="top";
$z[4][4]['currentstyle']="<li><a href='list.php?tid=~id~'>~typename~</a></li>";

?>