<?php
$z[0]=Array("global","",98,124);
$z[0][4]=array();
$z[0][4]['name']="cfg_welcome";
$z[1]=Array("type","<a href=\"[field:typelink /]\" >[field:typename /]</a>",288,375);
$z[1][4]=array();
$z[1][4]['typeid']="13";
$z[2]=Array("global","",656,682);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","(@me==\"\")? @me=\" class='navcurrent'\":@me=\"\";",776,870);
$z[3][4]=array();
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("channel","\r\n           <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n          ",916,1130);
$z[4][4]=array();
$z[4][4]['type']="top";
$z[4][4]['row']="6";
$z[4][4]['currentstyle']="<li class='navcurrent'><a href='~typelink~' >~typename~</a> </li>";

?>